routes/frontend.php
<?php

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

routes/web.php
<?php

Auth::routes();
Route::get('/', 'HomeController@index');
//Admin
Route::get('admin','Backend\Auth\AdminLoginController@index');
Route::get('login', 'Backend\Auth\AdminLoginController@showLoginForm')->name('show_login_form');
    Route::post('login', 'Backend\Auth\AdminLoginController@login')->name('login');
    Route::middleware('auth:admin')->group(function () {
        Route::post('Backend\logout', 'Backend\Auth\AdminLoginController@logout')->name('logout');
        Route::get('dashboard', 'Backend\BackendController@index')->name('dashboard');

        // Is Super Admin
        Route::middleware('isSuperAdmin')->group(function() {
            Route::get(
                'admins/search',
                'Backend\AdminController@search'
            )->name('admins.search');
            Route::put(
                'admins/active-status/{admin}',
                'Backend\AdminController@updateActiveStatus'
            )->name('admins.active-status.update');
            Route::resource('admins', 'Backend\AdminController');
        });


        Route::get(
            'users/search',
            'Backend\UserController@search'
        )->name('users.search');
        Route::put(
            'users/active-status/{user}',
            'Backend\UserController@updateActiveStatus'
        )->name('users.active-status.update');
        Route::resource('users', 'Backend\UserController');

        Route::resource('user-addresses', 'Backend\UserAddressController');

        Route::get(
            'vendors/search',
            'Backend\VendorController@search'
        )->name('vendors.search');
        Route::put(
            'vendors/active-status/{vendor}',
            'Backend\VendorController@updateActiveStatus'
        )->name('vendors.active-status.update');
        Route::resource('vendors', 'Backend\VendorController');

        
       
    });

app/Http/Controllers/Backend/CommonController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CommonController extends Controller
{
   
}

resources/views/backend/partials/commons/_bottom.blade.php
 <footer class="main-footer">
     <strong>Copyright © {{ date('Y') }} <a href="#">Sample_project</a>.</strong>
     All rights reserved.
 </footer>

resources/views/backend/partials/commons/_content_header.blade.php
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">{{ $title }}</h1>
            </div>
            <!-- <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Dashboard v2</li>
                </ol>
            </div> -->
        </div>
    </div>
</div>
<!-- /.content-header -->

resources/views/backend/partials/commons/_navbar.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        @auth('admin')
        <li class="nav-item d-flex flex-row align-items-center">
           {{ __('messages.welcome') }} {{ Auth::guard('admin')->user()->name }} :
            <a class="nav-link" href="{{ route('backend.logout') }}" role="button" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                {{ __('messages.logout') }}
                <form id="logout-form" action="{{ route('backend.logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </a>
        </li>
        @endauth
    </ul>
</nav>

resources/views/backend/partials/commons/_sidebar.blade.php
 <aside class="main-sidebar sidebar-dark-primary elevation-4">
     <!-- Brand Logo -->
     <a href="{{ route('backend.dashboard') }}" class="brand-link text-center">
         <span class="brand-text font-weight-light" style="">Sample_project</span>
     </a>

     <!-- Sidebar -->
     <div class="sidebar os-host os-theme-light os-host-overflow os-host-overflow-y os-host-resize-disabled os-host-scrollbar-horizontal-hidden os-host-transition">
         <div class="os-resize-observer-host">
             <div class="os-resize-observer observed"></div>
         </div>
         <div class="os-size-auto-observer">
             <div class="os-resize-observer observed"></div>
         </div>
         <div class="os-content-glue"></div>
         <div class="os-padding">
             <div class="os-viewport os-viewport-native-scrollbars-invisible os-viewport-native-scrollbars-overlaid">
                 <div class="os-content">
                     <!-- Sidebar Menu -->
                     <nav class="mt-2">
                         <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                             <!-- Add icons to the links using the .nav-icon class with font-awesome or any other icon font library -->
                             <li class="nav-item">
                                 <a href="{{ route('backend.dashboard') }}" class="nav-link @if (request()->is('backend')) active @endif">
                                     <i class="nav-icon fas fa-tachometer-alt" aria-hidden="true"></i>
                                     <p>
                                         {{ __('messages.dashboard') }}
                                     </p>
                                 </a>
                             </li>
                             @if(Auth::guard('admin')->user()->email == 'superadmin@example.com')
                             <li class="nav-item">
                                <a href="{{ route('backend.admins.index') }}"
                                    class="nav-link @if (request()->is('backend/admins*')) active @endif">
                                    <i class="nav-icon fas fa-user" aria-hidden="true"></i>
                                    <p>
                                        Admins
                                    </p>
                                </a>
                            </li>
                            @endif
                            
                            <li class="nav-item">
                                <a href="{{ route('backend.users.index') }}"
                                    class="nav-link @if (request()->is('backend/users*')) active @endif">
                                    <i class="nav-icon fas fa-users" aria-hidden="true"></i>
                                    <p>
                                        Users
                                    </p>
                                </a>
                            </li>
                            
                            <li class="nav-item">
                                <a href="{{ route('backend.vendors.index') }}"
                                    class="nav-link @if (request()->is('backend/vendors*')) active @endif">
                                    <i class="nav-icon fas fa-users-cog" aria-hidden="true"></i>
                                    <p>
                                        Vendors
                                    </p>
                                </a>
                            </li>
                         
                         </ul>
                     </nav>
                     <!-- /.sidebar-menu -->
                 </div>
             </div>
         </div>
         <div class="os-scrollbar os-scrollbar-horizontal os-scrollbar-unusable os-scrollbar-auto-hidden">
             <div class="os-scrollbar-track">
                 <div class="os-scrollbar-handle"></div>
             </div>
         </div>
         <div class="os-scrollbar os-scrollbar-vertical os-scrollbar-auto-hidden">
             <div class="os-scrollbar-track">
                 <div class="os-scrollbar-handle"></div>
             </div>
         </div>
         <div class="os-scrollbar-corner"></div>
     </div>
     <!-- /.sidebar -->
 </aside>