routes/frontend.php
<?php

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

routes/web.php
<?php

Auth::routes();
Route::get('/', 'HomeController@index');
//Admin
Route::get('admin','Backend\Auth\AdminLoginController@index');
Route::get('login', 'Backend\Auth\AdminLoginController@showLoginForm')->name('show_login_form');
    Route::post('login', 'Backend\Auth\AdminLoginController@login')->name('login');
    Route::middleware('auth:admin')->group(function () {
        Route::post('Backend\logout', 'Backend\Auth\AdminLoginController@logout')->name('logout');
        Route::get('dashboard', 'Backend\BackendController@index')->name('dashboard');

        // Is Super Admin
        Route::middleware('isSuperAdmin')->group(function() {
            Route::get(
                'admins/search',
                'Backend\AdminController@search'
            )->name('admins.search');
            Route::put(
                'admins/active-status/{admin}',
                'Backend\AdminController@updateActiveStatus'
            )->name('admins.active-status.update');
            Route::resource('admins', 'Backend\AdminController');
        });


        Route::get(
            'users/search',
            'Backend\UserController@search'
        )->name('users.search');
        Route::put(
            'users/active-status/{user}',
            'Backend\UserController@updateActiveStatus'
        )->name('users.active-status.update');
        Route::resource('users', 'Backend\UserController');

        Route::resource('user-addresses', 'Backend\UserAddressController');

        Route::get(
            'vendors/search',
            'Backend\VendorController@search'
        )->name('vendors.search');
        Route::put(
            'vendors/active-status/{vendor}',
            'Backend\VendorController@updateActiveStatus'
        )->name('vendors.active-status.update');
        Route::resource('vendors', 'Backend\VendorController');

        
       
    });

app/Http/Controllers/Backend/AdminController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Role;
use App\Admin;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;
use App\Http\Requests\Backend\StoreOrUpdateAdminRequest;

class AdminController extends Controller
{
    protected $perPage = 10;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $admins = Admin::admin()
            ->latest()
            ->paginate($this->perPage);

        return view('backend.admins.index', compact('admins'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::where('id','!=', 1)
            ->orderBy('name')
            ->pluck('name', 'id');

        return view('backend.admins.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreOrUpdateAdminRequest $request)
    {
        Admin::create([
            'role_id' => $request->role_id,
            'name' => $request->name,
            'email' => $request->email,
            'password' => Hash::make($request->password),
            'is_active' => $request->is_active
        ]);

        return redirect()
            ->route('backend.admins.index')
            ->withSuccess('The admin has been created.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $admin = Admin::with('role')->findOrFail($id);

        return view('backend.admins.show', compact('admin'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $roles = Role::orderBy('name')->where('id','!=', 1)->pluck('name', 'id');
        $admin = Admin::findOrFail($id);

        return view('backend.admins.edit', compact('admin', 'roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreOrUpdateAdminRequest $request, $id)
    {
        $admin = Admin::findOrFail($id);

        $admin->update([
            'name' => $request->name,
            'email' => $request->email,
            'password' => $request->password ? Hash::make($request->password) : $admin->password,
            'is_active' => $request->is_active
        ]);

        return redirect()
            ->route('backend.admins.index')
            ->withSuccess('The admin has been updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Admin::destroy($id);

        return response()->json([
            'status' => 'success',
            'message' => 'The admin has been removed.'
        ]);
    }

    public function search(Request $request)
    {
        $query = Admin::query();
        if ($request->filled('keywords')) {
            $query->where('name', 'LIKE', '%' . $request->keywords . '%')
                ->orWhere('email', 'LIKE', '%' . $request->keywords . '%');
        }
        $admins = $query->admin()
            ->orderBy('name')
            ->paginate($this->perPage);

        $admins->appends(['keywords' => $request->keywords]);

        return view('backend.admins.index', compact('admins'));
    }

    public function updateActiveStatus($id, Request $request)
    {
        $admin = Admin::findOrFail($id);
        $admin->update(['is_active' => $request->is_active]);

        return response()->json([
            'status' => 'success',
            'message' => 'The admin active status has been updated.'
        ]);
    }
}

app/Http/Controllers/Backend/BackendController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;
use Illuminate\Http\Request;
use App\Http\Requests\Backend\ImageUploadRequest;
use App\Admin;
use App\User;
use App\Vendor;

class BackendController extends Controller
{
    public function index()
    {
        $totalAdmins = Admin::where('role_id','!=',1)->count();
        $totalUsers = User::count();
        $totalVendors = Vendor::count();

        return view('backend.index', compact(
            'totalAdmins',
            'totalUsers',
            'totalVendors'
        ));
    }
}

app/Http/Controllers/Backend/CommonController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CommonController extends Controller
{
   
}

app/Http/Controllers/Backend/UserAddressController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\UserAddress;
use App\User;

class UserAddressController extends Controller
{
    public function destroy($id)
    {
        $userAddress = UserAddress::findOrFail($id);

        $userAddress->delete();

        return response()->json([
            'status' => 'success',
            'message' => 'The user address has been removed.'
        ]);
    }
}

app/Http/Controllers/Backend/UserController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use App\User;
use App\UserAddress;
use App\Http\Requests\Backend\StoreOrUpdateUserRequest;

class UserController extends Controller
{
    protected $perPage = 10;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::latest()
            ->paginate($this->perPage);
        return view('backend.users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view ('backend.users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreOrUpdateUserRequest $request)
    {
        //vendor image
        $image = $request->file('image');
        $name = Str::random(10).'.'.$image->extension();
        $image->move(public_path().'/images/user_images/', $name);  
        $image=$name;

        $user = User::create([
                'name' => $request->name,
                'phone' => $request->phone,
                'email' => $request->email,
                'image' => $image,
                'activation_code' => "",
                'register_source' => "panel",
                'testing_status' => $request->testing_status,
                'is_active' => $request->is_active,
                'token' => "",
                'last_login' => now(),
            ]);

        $totalAddress = count($request->address);

        for($i=0; $i < $totalAddress; $i++){
            UserAddress::create([
                'user_id' => $user->id,
                'address' => $request->input('address.' . $i),
                'phone' => $request->input('address_phone.' . $i),
                'type'  => $request->input('type.' . $i),
                'lat'   => $request->input('lat.' . $i),
                'lng'   => $request->input('lng.' . $i),
                'loc_name' => $request->input('loc_name.' . $i)
            ]);
        }
       
        return redirect()
            ->route('backend.users.index')
            ->withSuccess('The user has been created.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::findOrFail($id);
        $userAddresses = UserAddress::where('user_id',$id)->get();

        return view('backend.users.show', compact('user','userAddresses'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);
        $userAddresses = UserAddress::where('user_id',$id)->get();

        return view('backend.users.edit', compact('user','userAddresses'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreOrUpdateUserRequest $request, $id)
    {
        $user = User::findOrFail($id);

        //vendor image
        $image = $request->hidden_image;
        $user_image = $request->file('image');
        if($user_image !== null){
            $name = Str::random(10).'.'.$user_image->extension();
            $user_image->move(public_path().'/images/user_images/', $name);  
            $image=$name;

            $photo = public_path("images/user_images/").$request->hidden_image;

            if(file_exists($photo)){
                @unlink($photo);
            }
        }

        $user->update([
            'name' => $request->name,
            'phone' => $request->phone,
            'email' => $request->email,
            'image' => $image,
            'activation_code' => "",
            'register_source' => "panel",
            'testing_status' => $request->testing_status,
            'is_active' => $request->is_active,
            'token' => "",
            'last_login' => now(),
        ]);

        $totalAddress = count($request->address);

        for($i=0; $i < $totalAddress; $i++){

            $user_address = UserAddress::find($request->input('id.' . $i));
            if($user_address){
                $user_address->update([
                    'user_id' => $user->id,
                    'address' => $request->input('address.' . $i),
                    'phone' => $request->input('address_phone.' . $i),
                    'type'  => $request->input('type.' . $i),
                    'lat'   => $request->input('lat.' . $i),
                    'lng'   => $request->input('lng.' . $i),
                    'loc_name' => $request->input('loc_name.' . $i)
                ]);
            }else{
                UserAddress::create([
                    'user_id' => $user->id,
                    'address' => $request->input('address.' . $i),
                    'phone' => $request->input('address_phone.' . $i),
                    'type'  => $request->input('type.' . $i),
                    'lat'   => $request->input('lat.' . $i),
                    'lng'   => $request->input('lng.' . $i),
                    'loc_name' => $request->input('loc_name.' . $i)
                ]);
            }
        }
       
        return redirect()
            ->route('backend.users.index')
            ->withSuccess('The user has been updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);

        $image = public_path("images/user_images/").$user->image;

        if(file_exists($image)){
            @unlink($image);
        }

        $user->delete();

        return response()->json([
            'status' => 'success',
            'message' => 'The user has been removed.'
        ]);
    }

    public function search(Request $request)
    {
        $query = User::query();
        if ($request->filled('keywords')) {
            $query->where('name', 'LIKE', '%' . $request->keywords . '%');
        }
        $users = $query->orderBy('name')
            ->paginate($this->perPage);

        $users->appends(['keywords' => $request->keywords]);

        return view('backend.users.index', compact('users'));
    }

    public function updateActiveStatus($id, Request $request)
    {
        $user = User::findOrFail($id);
        $user->update(['is_active' => $request->is_active]);

        return response()->json([
            'status' => 'success',
            'message' => 'The user active status has been updated.'
        ]);
    }
}

resources/views/backend/admins/create.blade.php
@extends('layouts.backend')
@section('title', 'Create Admin')
@section('content')
@include('backend.partials.commons._content_header', ['title' => 'Create Admin'])
<section class="content">
    <div class="card">
        <form action="{{ route('backend.admins.store') }}" method="POST">
            @csrf
            <div class="card-body">
                <div class="form-group col-md-6">
                    <div class="mb-0 alert alert-warning">
                        <i class="fas fa-exclamation-triangle"></i>
                        &nbsp;Attributes marked as <span class="text-danger">*</span> are required.
                    </div>
                </div>
                <div class="form-group col-md-6">
                    <label for="school">Role <span class="text-danger">*</span></label>
                    <select name="role_id" id="school" class="form-control js-select-2 @error('role_id') is-invalid @enderror"  data-selected="{{ old('role_id', 0) }}">
                        <option value="0">Select Role</option>
                        @if($roles->isNotEmpty())
                        @foreach($roles as $key => $value)
                        <option value="{{ $key }}">{{ $value }}</option>
                        @endforeach
                        @endif
                    </select>
                    @error('role_id')
                    <span id="role_id-error" class="error invalid-feedback">
                        {{ $message }}
                    </span>
                    @enderror
                </div>
                <div class="form-group col-md-6">
                    <label for="name">Name <span class="text-danger">*</span></label>
                    <input type="text" class="form-control @error('name') is-invalid @enderror" id="name"
                        name="name" placeholder="Enter Admin Name" value="{{ old('name') ?? '' }}">
                    @error('name')
                    <span id="name-error" class="error invalid-feedback">
                        {{ $message }}
                    </span>
                    @enderror
                </div>
                <div class="form-group col-md-6">
                    <label for="email">Email <span class="text-danger">*</span></label>
                    <input type="text" class="form-control @error('email') is-invalid @enderror" id="email"
                        name="email" placeholder="Enter Admin Email" value="{{ old('email', '') }}">
                    @error('email')
                    <span id="email-error" class="error invalid-feedback">
                        {{ $message }}
                    </span>
                    @enderror
                </div>
                <div class="form-group col-md-6">
                    <label for="password">Password <span class="text-danger">*</span> <a href="javascript:void(0);"
                            id="toggle-password"><small>Show
                                Password</small></a></label>
                    <input type="password" class="form-control @error('password') is-invalid @enderror"
                        id="password" name="password" placeholder="Enter Admin Password"
                        value="{{ old('password') ?? '' }}">
                    @error('password')
                    <span id="password-error" class="error invalid-feedback">
                        {{ $message }}
                    </span>
                    @enderror
                </div>
                <div class="form-group col-md-6">
                    <label for="confirm-password">Confirm Password <span class="text-danger">*</span> 
                         <a href="javascript:void(0);" id="toggle-confirm-password"><small>Show
                                Password</small></a></label>
                    <input type="password"
                        class="form-control @error('password_confirmation') is-invalid @enderror"
                        id="confirm-password" name="password_confirmation" placeholder="Enter Admin Confirm Password"
                        value="{{ old('password_confirmation') ?? '' }}">
                    @error('password_confirmation')
                    <span id="confirm-password-error" class="error invalid-feedback">
                        {{ $message }}
                    </span>
                    @enderror
                </div>
                <div class="form-group col-md-6">
                    <label for="is-active">
                        Active
                        <span class="text-danger">*</span>
                    </label>
                    <div class="form-inline">
                        <div class="icheck-primary mr-2">
                            <input type="radio" id="yes" name="is_active" value="1" checked />
                            <label for="yes">Yes</label>
                        </div>
                        <div class="icheck-primary mr-2">
                            <input type="radio" id="no" name="is_active" value="0" />
                            <label for="no">No</label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <div class="col-md-6 px-0 d-flex justify-content-between">
                    <a href="{{ route('backend.admins.index') }}" class="btn btn-flat btn-primary">
                        <i class="fas fa-chevron-left"></i>
                        <span>Back</span>
                    </a>
                    <button type="submit" class="btn btn-flat btn-success">Save</button>
                </div>
            </div>
        </form>
    </div>
</section>
@endsection

resources/views/backend/admins/edit.blade.php
@extends('layouts.backend')
@section('title', 'Edit '. $admin->name)
@section('content')
@include('backend.partials.commons._content_header', ['title' => 'Edit '. $admin->name])
<section class="content">
    <div class="card">
        <form action="{{ route('backend.admins.update', $admin->id) }}" method="POST">
            @csrf
            @method('PUT')
            <div class="card-body">
                <div class="form-group col-md-6">
                    <div class="mb-0 alert alert-warning">
                        <i class="fas fa-exclamation-triangle"></i>
                        &nbsp;Attributes marked as <span class="text-danger">*</span> are required.
                    </div>
                </div>
                <div class="form-group col-md-6">
                    <label for="role">Role<span class="text-danger">*</span></label>
                    <select name="role_id" id="role" class="form-control js-select-2 @error('role_id') @enderror" data-selected="{{ old('role_id', $admin->role->id) }}">
                        <option value="0">Select Role</option>
                        @if($roles->isNotEmpty())
                        @foreach($roles as $key => $value)
                        <option value="{{ $key }}">{{ $value }}</option>
                        @endforeach
                        @endif
                    </select>
                    @error('role_id')
                    <span id="role-error" class="error invalid-feedback">
                        {{ $message }}
                    </span>
                    @enderror
                </div>
                <div class="form-group col-md-6">
                    <label for="name">Name <span class="text-danger">*</span></label>
                    <input type="text" class="form-control @error('name') is-invalid @enderror" id="name"
                        name="name" placeholder="Enter admin Name" value="{{ old('name') ?? $admin->name }}">
                    @error('name')
                    <span id="name-error" class="error invalid-feedback">
                        {{ $message }}
                    </span>
                    @enderror
                </div>
                <div class="form-group col-md-6">
                    <label for="email">Email <span class="text-danger">*</span></label>
                    <input type="text" class="form-control @error('email') is-invalid @enderror" id="email"
                        name="email" placeholder="Enter Admin Email" value="{{ old('email') ?? $admin->email }}">
                    @error('email')
                    <span id="email-error" class="error invalid-feedback">
                        {{ $message }}
                    </span>
                    @enderror
                </div>
                <div class="form-group col-md-6">
                    <label for="password">Password <span class="text-danger">*</span> <a href="javascript:void(0);"
                            id="toggle-password"><small>Show
                                Password</small></a></label>
                    <input type="password" class="form-control @error('password') is-invalid @enderror"
                        id="password" name="password" placeholder="Enter Admin Password"
                        value="{{ old('password') ?? '' }}">
                    @error('password')
                    <span id="password-error" class="error invalid-feedback">
                        {{ $message }}
                    </span>
                    @enderror
                </div>
                <div class="form-group col-md-6">
                    <label for="confirm-password">Confirm Password <span class="text-danger">*</span> 
                         <a href="javascript:void(0);" id="toggle-confirm-password"><small>Show
                                Password</small></a></label>
                    <input type="password"
                        class="form-control @error('password_confirmation') is-invalid @enderror"
                        id="confirm-password" name="password_confirmation" placeholder="Enter Admin Confirm Password"
                        value="{{ old('password_confirmation') ?? '' }}">
                    @error('password_confirmation')
                    <span id="confirm-password-error" class="error invalid-feedback">
                        {{ $message }}
                    </span>
                    @enderror
                </div>
                <div class="form-group col-md-6">
                    <label for="is-active">
                        Active
                        <span class="text-danger">*</span>
                    </label>
                    <div class="form-inline">
                        <div class="icheck-primary mr-2">
                            <input type="radio" id="yes" name="is_active" value="1" @if($admin->is_active == 1) checked @endif />
                            <label for="yes">Yes</label>
                        </div>
                        <div class="icheck-primary mr-2">
                            <input type="radio" id="no" name="is_active" value="0" @if($admin->is_active == 0) checked @endif/>
                            <label for="no">No</label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <div class="col-md-6 px-0 d-flex justify-content-between">
                    <a href="{{ route('backend.admins.index') }}" class="btn btn-flat btn-primary">
                        <i class="fas fa-chevron-left"></i>
                        <span>Back</span>
                    </a>
                    <button type="submit" class="btn btn-flat btn-success">Save</button>
                </div>
            </div>
        </form>
    </div>
</section>
@endsection

resources/views/backend/admins/show.blade.php
@extends('layouts.backend')
@section('title', $admin->name)
@section('content')
@include('backend.partials.commons._content_header', ['title' => $admin->name])
<section class="content">
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-md-12">
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <tr>
                                <td>Role:</td>
                                <td>{{ $admin->role->name }}</td>
                            </tr>
                            <tr>
                                <td>Email:</td>
                                <td>{{ $admin->email }}</td>
                            </tr>
                            <tr>
                                <td>Active:</td>
                                <td>
                                    @if($admin->is_active)
                                    <span class="badge-btn bg-success">Yes</span>
                                    @else
                                    <span class="badge-btn bg-danger">No</span>
                                    @endif
                                </td>
                            </tr>
                            <tr>
                                <td>Created at: </td>
                                <td>{{ $admin->created_at }}</td>
                            </tr>
                            <tr>
                                <td>Updated at: </td>
                                <td>{{ $admin->updated_at }}</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <div class="col-md-4 px-0">
                <a href="{{ route('backend.admins.index') }}" class="btn btn-flat btn-primary">
                    <i class="fas fa-chevron-left"></i>
                    <span>Back</span>
                </a>
            </div>
        </div>
    </div>
</section>
@endsection
@section('js')
@endsection