routes/frontend.php
<?php

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

routes/web.php
<?php

Auth::routes();
Route::get('/', 'HomeController@index');
//Admin
Route::get('admin','Backend\Auth\AdminLoginController@index');
Route::get('login', 'Backend\Auth\AdminLoginController@showLoginForm')->name('show_login_form');
    Route::post('login', 'Backend\Auth\AdminLoginController@login')->name('login');
    Route::middleware('auth:admin')->group(function () {
        Route::post('Backend\logout', 'Backend\Auth\AdminLoginController@logout')->name('logout');
        Route::get('dashboard', 'Backend\BackendController@index')->name('dashboard');

        // Is Super Admin
        Route::middleware('isSuperAdmin')->group(function() {
            Route::get(
                'admins/search',
                'Backend\AdminController@search'
            )->name('admins.search');
            Route::put(
                'admins/active-status/{admin}',
                'Backend\AdminController@updateActiveStatus'
            )->name('admins.active-status.update');
            Route::resource('admins', 'Backend\AdminController');
        });


        Route::get(
            'users/search',
            'Backend\UserController@search'
        )->name('users.search');
        Route::put(
            'users/active-status/{user}',
            'Backend\UserController@updateActiveStatus'
        )->name('users.active-status.update');
        Route::resource('users', 'Backend\UserController');

        Route::resource('user-addresses', 'Backend\UserAddressController');

        Route::get(
            'vendors/search',
            'Backend\VendorController@search'
        )->name('vendors.search');
        Route::put(
            'vendors/active-status/{vendor}',
            'Backend\VendorController@updateActiveStatus'
        )->name('vendors.active-status.update');
        Route::resource('vendors', 'Backend\VendorController');

        
       
    });

app/Vendor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Vendor extends Model
{
    use SoftDeletes;
    protected $fillable = [
        'name',
        'phone',
        'address',
        'image',
        'join_date',
        'permanent_date',
        'attached_files',
        'is_active'
    ];
    public function vendorotps()
    {
        return $this->hasMany(VendorOtp::class);
    }
    public function vendortokens()
    {
        return $this->hasMany(VendorTokens::class);
    }
}

app/Http/Controllers/Backend/AdminController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Role;
use App\Admin;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;
use App\Http\Requests\Backend\StoreOrUpdateAdminRequest;

class AdminController extends Controller
{
    protected $perPage = 10;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $admins = Admin::admin()
            ->latest()
            ->paginate($this->perPage);

        return view('backend.admins.index', compact('admins'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::where('id','!=', 1)
            ->orderBy('name')
            ->pluck('name', 'id');

        return view('backend.admins.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreOrUpdateAdminRequest $request)
    {
        Admin::create([
            'role_id' => $request->role_id,
            'name' => $request->name,
            'email' => $request->email,
            'password' => Hash::make($request->password),
            'is_active' => $request->is_active
        ]);

        return redirect()
            ->route('backend.admins.index')
            ->withSuccess('The admin has been created.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $admin = Admin::with('role')->findOrFail($id);

        return view('backend.admins.show', compact('admin'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $roles = Role::orderBy('name')->where('id','!=', 1)->pluck('name', 'id');
        $admin = Admin::findOrFail($id);

        return view('backend.admins.edit', compact('admin', 'roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreOrUpdateAdminRequest $request, $id)
    {
        $admin = Admin::findOrFail($id);

        $admin->update([
            'name' => $request->name,
            'email' => $request->email,
            'password' => $request->password ? Hash::make($request->password) : $admin->password,
            'is_active' => $request->is_active
        ]);

        return redirect()
            ->route('backend.admins.index')
            ->withSuccess('The admin has been updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Admin::destroy($id);

        return response()->json([
            'status' => 'success',
            'message' => 'The admin has been removed.'
        ]);
    }

    public function search(Request $request)
    {
        $query = Admin::query();
        if ($request->filled('keywords')) {
            $query->where('name', 'LIKE', '%' . $request->keywords . '%')
                ->orWhere('email', 'LIKE', '%' . $request->keywords . '%');
        }
        $admins = $query->admin()
            ->orderBy('name')
            ->paginate($this->perPage);

        $admins->appends(['keywords' => $request->keywords]);

        return view('backend.admins.index', compact('admins'));
    }

    public function updateActiveStatus($id, Request $request)
    {
        $admin = Admin::findOrFail($id);
        $admin->update(['is_active' => $request->is_active]);

        return response()->json([
            'status' => 'success',
            'message' => 'The admin active status has been updated.'
        ]);
    }
}

app/Http/Controllers/Backend/BackendController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;
use Illuminate\Http\Request;
use App\Http\Requests\Backend\ImageUploadRequest;
use App\Admin;
use App\User;
use App\Vendor;

class BackendController extends Controller
{
    public function index()
    {
        $totalAdmins = Admin::where('role_id','!=',1)->count();
        $totalUsers = User::count();
        $totalVendors = Vendor::count();

        return view('backend.index', compact(
            'totalAdmins',
            'totalUsers',
            'totalVendors'
        ));
    }
}

app/Http/Controllers/Backend/CommonController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CommonController extends Controller
{
   
}

app/Http/Controllers/Backend/UserAddressController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\UserAddress;
use App\User;

class UserAddressController extends Controller
{
    public function destroy($id)
    {
        $userAddress = UserAddress::findOrFail($id);

        $userAddress->delete();

        return response()->json([
            'status' => 'success',
            'message' => 'The user address has been removed.'
        ]);
    }
}

app/Http/Controllers/Backend/UserController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use App\User;
use App\UserAddress;
use App\Http\Requests\Backend\StoreOrUpdateUserRequest;

class UserController extends Controller
{
    protected $perPage = 10;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::latest()
            ->paginate($this->perPage);
        return view('backend.users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view ('backend.users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreOrUpdateUserRequest $request)
    {
        //vendor image
        $image = $request->file('image');
        $name = Str::random(10).'.'.$image->extension();
        $image->move(public_path().'/images/user_images/', $name);  
        $image=$name;

        $user = User::create([
                'name' => $request->name,
                'phone' => $request->phone,
                'email' => $request->email,
                'image' => $image,
                'activation_code' => "",
                'register_source' => "panel",
                'testing_status' => $request->testing_status,
                'is_active' => $request->is_active,
                'token' => "",
                'last_login' => now(),
            ]);

        $totalAddress = count($request->address);

        for($i=0; $i < $totalAddress; $i++){
            UserAddress::create([
                'user_id' => $user->id,
                'address' => $request->input('address.' . $i),
                'phone' => $request->input('address_phone.' . $i),
                'type'  => $request->input('type.' . $i),
                'lat'   => $request->input('lat.' . $i),
                'lng'   => $request->input('lng.' . $i),
                'loc_name' => $request->input('loc_name.' . $i)
            ]);
        }
       
        return redirect()
            ->route('backend.users.index')
            ->withSuccess('The user has been created.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::findOrFail($id);
        $userAddresses = UserAddress::where('user_id',$id)->get();

        return view('backend.users.show', compact('user','userAddresses'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);
        $userAddresses = UserAddress::where('user_id',$id)->get();

        return view('backend.users.edit', compact('user','userAddresses'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreOrUpdateUserRequest $request, $id)
    {
        $user = User::findOrFail($id);

        //vendor image
        $image = $request->hidden_image;
        $user_image = $request->file('image');
        if($user_image !== null){
            $name = Str::random(10).'.'.$user_image->extension();
            $user_image->move(public_path().'/images/user_images/', $name);  
            $image=$name;

            $photo = public_path("images/user_images/").$request->hidden_image;

            if(file_exists($photo)){
                @unlink($photo);
            }
        }

        $user->update([
            'name' => $request->name,
            'phone' => $request->phone,
            'email' => $request->email,
            'image' => $image,
            'activation_code' => "",
            'register_source' => "panel",
            'testing_status' => $request->testing_status,
            'is_active' => $request->is_active,
            'token' => "",
            'last_login' => now(),
        ]);

        $totalAddress = count($request->address);

        for($i=0; $i < $totalAddress; $i++){

            $user_address = UserAddress::find($request->input('id.' . $i));
            if($user_address){
                $user_address->update([
                    'user_id' => $user->id,
                    'address' => $request->input('address.' . $i),
                    'phone' => $request->input('address_phone.' . $i),
                    'type'  => $request->input('type.' . $i),
                    'lat'   => $request->input('lat.' . $i),
                    'lng'   => $request->input('lng.' . $i),
                    'loc_name' => $request->input('loc_name.' . $i)
                ]);
            }else{
                UserAddress::create([
                    'user_id' => $user->id,
                    'address' => $request->input('address.' . $i),
                    'phone' => $request->input('address_phone.' . $i),
                    'type'  => $request->input('type.' . $i),
                    'lat'   => $request->input('lat.' . $i),
                    'lng'   => $request->input('lng.' . $i),
                    'loc_name' => $request->input('loc_name.' . $i)
                ]);
            }
        }
       
        return redirect()
            ->route('backend.users.index')
            ->withSuccess('The user has been updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);

        $image = public_path("images/user_images/").$user->image;

        if(file_exists($image)){
            @unlink($image);
        }

        $user->delete();

        return response()->json([
            'status' => 'success',
            'message' => 'The user has been removed.'
        ]);
    }

    public function search(Request $request)
    {
        $query = User::query();
        if ($request->filled('keywords')) {
            $query->where('name', 'LIKE', '%' . $request->keywords . '%');
        }
        $users = $query->orderBy('name')
            ->paginate($this->perPage);

        $users->appends(['keywords' => $request->keywords]);

        return view('backend.users.index', compact('users'));
    }

    public function updateActiveStatus($id, Request $request)
    {
        $user = User::findOrFail($id);
        $user->update(['is_active' => $request->is_active]);

        return response()->json([
            'status' => 'success',
            'message' => 'The user active status has been updated.'
        ]);
    }
}

resources/views/backend/vendors/create.blade.php
@extends('layouts.backend')
@section('title', 'Create Vendor')
@section('content')
@include('backend.partials.commons._content_header', ['title' => 'Create Vendor'])
<section class="content">
    <div class="card">
        <form action="{{ route('backend.vendors.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="card-body">
                <div class="form-group col-md-6">
                    <div class="mb-0 alert alert-warning">
                        <i class="fas fa-exclamation-triangle"></i>
                        &nbsp;Attributes marked as <span class="text-danger">*</span> are required.
                    </div>
                </div>
                
                <div class="form-group col-md-6">
                    <label for="name">Name <span class="text-danger">*</span></label>
                    <input type="text" class="form-control @error('name') is-invalid @enderror" id="name"
                        name="name" placeholder="Enter Vendor Name" value="{{ old('name', '') }}">
                    @error('name')
                    <span id="name-error" class="error invalid-feedback">
                        {{ $message }}
                    </span>
                    @enderror
                </div>

                <div class="form-group col-md-6">
                    <label for="phone">Phone <span class="text-danger">*</span></label>
                    <input type="number" class="form-control @error('phone') is-invalid @enderror" id="phone"
                        name="phone" placeholder="Enter Vendor's Phone" value="{{ old('phone', '') }}">
                    @error('phone')
                    <span id="phone-error" class="error invalid-feedback">
                        {{ $message }}
                    </span>
                    @enderror
                </div>

                <div class="form-group col-md-6">
                    <label for="address">Address <span class="text-danger">*</span></label>
                    <input type="text" class="form-control @error('address') is-invalid @enderror" id="address"
                        name="address" placeholder="Enter Vendor Address" value="{{ old('address', '') }}">
                    @error('address')
                    <span id="address-error" class="error invalid-feedback">
                        {{ $message }}
                    </span>
                    @enderror
                </div>

                <!-- <div class="form-group col-md-6">
                    <label for="image">Vendor Image <span class="text-danger">*</span></label>
                    <div id="react-image-upload" data-old-image-path="{{ old('image_path') ?? '' }}"
                        @error('image_path') data-required-error="{{ $message }}" @enderror data-preview-class="cover-image"></div>
                    <div class="text-warning mt-2">
                        <i class="fas fa-info-circle"></i>
                        <small>File size must be maximum 2 MB.</small>
                    </div>
                </div> -->

                <div class="form-group col-md-6">
                    <label for="image">Vendor Photo <span class="text-danger">*</span></label>
                    <input type="file" class="form-control @error('image') is-invalid @enderror" id="image" name="image" value="{{ old('image', '') }}">
                    @error('image')
                    <span id="attached-files-error" class="error invalid-feedback">
                        {{ $message }}
                    </span>
                    @enderror
                </div>

                <div class="form-group col-md-6">
                    <label for="join-date">Join Date <span class="text-danger">*</span></label>
                    <input type="date" class="form-control @error('join_date') is-invalid @enderror" id="join-date" name="join_date" value="{{ old('join_date', now()->format('Y-m-d')) }}">
                    @error('join_date')
                    <span id="join-date-error" class="error invalid-feedback">
                        {{ $message }}
                    </span>
                    @enderror
                </div>

                <div class="form-group col-md-6">
                    <label for="permanent-date">Permanent Date <span class="text-danger">*</span></label>
                    <input type="date" class="form-control @error('permanent_date') is-invalid @enderror" id="permanent-date" name="permanent_date" value="{{ old('permanent_date', now()->format('Y-m-d')) }}">
                    @error('permanent_date')
                    <span id="permanent-date-error" class="error invalid-feedback">
                        {{ $message }}
                    </span>
                    @enderror
                </div>

                <div class="form-group col-md-6">
                    <label for="attached-files">Attached Files <span class="text-danger">*</span></label>
                    <input type="file" class="form-control @error('attached_files') is-invalid @enderror" id="attached-files" name="attached_files[]" value="{{ old('attached_files', '') }}" multiple required>
                    @error('attached_files')
                    <span id="attached-files-error" class="error invalid-feedback">
                        {{ $message }}
                    </span>
                    @enderror
                </div>

                <div class="form-group col-md-6">
                    <label for="is-active">
                        Active
                        <span class="text-danger">*</span>
                    </label>
                    <div class="form-inline">
                        <div class="icheck-primary mr-2">
                            <input type="radio" id="yes" name="is_active" value="1"  />
                            <label for="yes">Yes</label>
                        </div>
                        <div class="icheck-primary mr-2">
                            <input type="radio" id="no" name="is_active" value="0" checked />
                            <label for="no">No</label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <div class="col-md-6 px-0 d-flex justify-content-between">
                    <a href="{{ route('backend.vendors.index') }}" class="btn btn-flat btn-primary">
                        <i class="fas fa-chevron-left"></i>
                        <span>Back</span>
                    </a>
                    <button type="submit" class="btn btn-flat btn-success">Save</button>
                </div>
            </div>
        </form>
    </div>
</section>
@endsection
@section('js')
@endsection

resources/views/backend/vendors/index.blade.php
@extends('layouts.backend')
@section('title', 'Vendors')
@section('content')
@include('backend.partials.commons._content_header', ['title' => 'Vendors'])
@if(session()->has('success'))
<div id="swal" data-icon="success" data-title="Success!" data-message="{{ session('success') }}"></div>
@endif
<section class="content">
    <div class="card">
        <div class="card-body">
             <div class="row mb-2">
                <div class="col-md-10 col-12">
                    <form action="{{ route('backend.vendors.search') }}" method="GET">
                        <div class="row">
                            <div class="col-12">
                                <label for="search">Search: </label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 col-12">
                                <div class="form-group">
                                    <input type="text" class="form-control" id="search" name="keywords"
                                        value="{{ request()->query('keywords') ?? '' }}" placeholder="Enter Keywords">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <button class="btn btn-flat btn-primary mr-2">
                                    <i class="fas fa-search"></i>
                                    <span>Search</span>
                                </button>
                                <a href="{{ route('backend.vendors.index') }}" class="btn btn-flat btn-info">
                                    <i class="fas fa-times"></i>
                                    <span>Cancel</span>
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-md-2 col-12">
                    <a href="{{ route('backend.vendors.create') }}"
                        class="btn btn-flat btn-success mt-2 mt-md-0 float-md-right">
                        <i class="fas fa-plus"></i>
                        <span>Create Vendor</span>
                    </a>
                </div>
            </div>
            <div class="row mb-2">
                <div class="col-12">
                    <p class="mb-0">
                        Showing <span class="font-weight-bold">{{ $vendors->firstItem() ?? 0 }}</span> to
                        <span class="font-weight-bold">{{ $vendors->lastItem() ?? 0 }}</span>
                        of
                        <span class="font-weight-bold">{{ $vendors->total() ?? 0 }}</span> entries
                    </p>
                </div>
            </div>
            <div class="table-responsive">
                <table class="table table-bordered table-striped">
                    <thead>
                        <th>#</th>
                        <th>Name</th>
                        <th>Phone</th>
                        <th>Address</th>
                        <th>Active</th>
                        <th>Actions</th>
                    </thead>
                    <tbody>
                        @php
                        $itemNo = $vendors->firstItem();
                        @endphp
                        @if(isset($vendors) && count($vendors) > 0)
                        @foreach($vendors as $vendor)
                        <tr>
                            <td>{{ $itemNo++ }}</td>
                            <td>{{ $vendor->name }}</td>
                            <td>{{ $vendor->phone }}</td>
                            <td>{{ $vendor->address }}</td>
                            <td>
                                <input type="checkbox" class="boostrap-switch" name="is_active"
                                    @if($vendor->is_active
                                == 1) checked @endif data-id="{{ $vendor->id }}" data-type="vendors">
                            </td>
                            <td>
                                <a href="{{ route('backend.vendors.show', $vendor->id) }}"
                                    data-toggle="popover" data-content="View" class="text-primary mx-2">
                                    <i class="fas fa-eye"></i>
                                </a>
                                <a href="{{ route('backend.vendors.edit', $vendor->id) }}"
                                    data-toggle="popover" data-content="Edit" class="text-gray mx-2">
                                    <i class="fas fa-edit"></i>
                                </a>
                                <a href="javascript:void(0);" data-toggle="popover" data-content="Remove"
                                    class="remove text-danger mx-2" data-id="{{ $vendor->id }}"
                                    data-remove-content="{{ $vendor->name }}" data-type="vendors">
                                    <i class="fas fa-trash-alt"></i>
                                </a>
                            </td>
                        </tr>
                        @endforeach
                        @else
                        <tr>
                            <td colspan="6" class="text-center">There is no item to display.</td>
                        </tr>
                        @endif
                    </tbody>
                </table>
            </div>
        </div>
        @if($vendors->total() > 10)
        <div class="card-footer d-flex justify-content-center">
            {{ $vendors->links() }}
        </div>
        @endif
    </div>
</section>
@endsection

resources/views/backend/vendors/show.blade.php
@extends('layouts.backend')
@section('title', $vendor->name)
@section('content')
@include('backend.partials.commons._content_header', ['title' => $vendor->name])
<section class="content">
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-md-8">
                    <table class="table no-border table-responsive">
                        <tr>
                            <td>Name:</td>
                            <td>{{ $vendor->name }}</td>
                        </tr>

                        <tr>
                            <td>Phone:</td>
                            <td>{{ $vendor->phone }}</td>
                        </tr>

                        <tr>
                            <td>Address:</td>
                            <td>{{ $vendor->address }}</td>
                        </tr>

                        <!-- <tr>
                            <td>Photo:</td>
                            <td>
                                <img src="{{ asset('images/vendor_images/'.$vendor->image)}}" class="img-thumbnail" width="75" />
                            </td>
                        </tr> -->

                        <tr>
                            <td>Join Date:</td>
                            <td>{{ $vendor->join_date }}</td>
                        </tr>

                        <tr>
                            <td>Permanent Date:</td>
                            <td>{{ $vendor->permanent_date }}</td>
                        </tr>

                        <tr>
                            <td>Attached Files:</td>
                            <td>
                                <?php 
                                    $attached_files = json_decode($vendor->attached_files); 
                                ?>
                                @foreach($attached_files as $attached_file)
                                    <img src="{{ asset('images/attached_files/'.$attached_file)}}" class="img-thumbnail" width="75" />
                                @endforeach
                            </td>
                        </tr>

                        <tr>
                            <td>Active:</td>
                            <td>
                                @if($vendor->is_active)
                                <span class="badge-btn bg-success">Yes</span>
                                @else
                                <span class="badge-btn bg-danger">No</span>
                                @endif
                            </td>
                        </tr>
                        <tr>
                            <td>Created at: </td>
                            <td>{{ $vendor->created_at }}</td>
                        </tr>
                        <tr>
                            <td>Updated at: </td>
                            <td>{{ $vendor->updated_at }}</td>
                        </tr>
                    </table>
                </div>
                <div class="col-md-4">
                    <img src="{{ asset('images/vendor_images/'.$vendor->image)}}" alt="{{ $vendor->name }}" class="image">
                </div>
            </div>
        </div>
        <div class="card-footer">
            <div class="col-md-4 px-0">
                <a href="{{ route('backend.vendors.index') }}" class="btn btn-flat btn-primary">
                    <i class="fas fa-chevron-left"></i>
                    <span>Back</span>
                </a>
            </div>
        </div>
    </div>
</section>
@endsection
@section('js')
@endsection